### ISSUE TITLE
realize list_buckets function in  different storage

### ISSUE THREAD

**Issue by krislavten** [bsc-s2/aws-s3-web-console#1]

**Comment by krislavten** [comment]
we can't call list_buckets API in different origin because the CROS in browsers, so i want to create a Node serve.

**Comment by drmingdrmer** [comment]
I didn't get it. Doesn't list-bucket send a OPTION request?

**Comment by krislavten** [comment]
> I didn't get it. Doesn't list-bucket send a OPTION request?

yes, and we can't set OPTION rules for list_buckets

**Comment by krislavten** [comment]
done. [node-server](https://github.com/bsc-s2/aws-s3-node-server)
